config/routes.rb
OnRuby::Application.routes.draw do
  namespace :admin do
    resources :events do
      post :duplicate, on: :collection
      post :connect, on: :member
    end
    resources :locations
    resources :topics
    resources :materials
    resources :highlights
    resources :jobs
    resources :users

    root to: 'events#index'
  end
  namespace :super_admin do
    resources :events do
      post :duplicate, on: :collection
      post :connect, on: :member
    end
    resources :locations
    resources :topics
    resources :materials
    resources :highlights
    resources :jobs
    resources :authorizations
    resources :likes
    resources :participants
    resources :users

    root to: 'events#index'
  end

  get 'image/:timestamp/:model_name/:model_id/*filename' => 'images#show', as: :image_dispatch

  resource :sitemap, only: :show

  resources :users do
    get :calendar, on: :member
  end

  resources :locations do
    get :none, on: :collection
  end

  resources :events do
    resources :materials
    resources :topics
    resources :participants
  end

  resources :topics do
    resources :likes
  end

  scope '/auth' do
    get '/',                         to: 'sessions#index', as: :login
    get '/:provider/callback',       to: 'sessions#create', as: :provider_callback
    get '/failure',                  to: 'sessions#failure'
    get '/destroy_session',          to: 'sessions#destroy', as: :destroy_session
    get '/offline_login/:nickname',  to: 'sessions#offline_login' if Rails.env.development?
  end

  scope "/sessions" do
    get "/email", to: "sessions#email"
    post "/email_login", to: "sessions#email_login"
  end

  constraints MainDomainConstraint.new do
    get '/', to: 'labels#index', as: :labels
  end

  scope '/api' do
    get '/', to: 'api#index', as: :api
    get '/flush', to: 'api#flush', as: :flush
  end

  root to: 'home#index'

  match '*path.php', via: :all, to: ->(_env) { [301, { 'Location' => 'http://www.youporn.com/' }, ['fuck yourself!']] }
  match '*path', via: :all, constraints: ->(request) { request.path !~ %r{\A/admin} }, to: ->(_env) { [404, { 'Content-Type' => 'text/html' }, ['not found']] }
end

app/models/topic.rb
# frozen_string_literal: true

class Topic < ApplicationRecord
  include Slug
  extend ApiHandling
  expose_api :id, :event_id, :user_id, :name, :description, :user

  PROPOSAL_TYPES = %w[proposal enquiry].freeze
  validates :user, :name, :description, :label, presence: true
  validates :proposal_type, inclusion: { in: PROPOSAL_TYPES }
  validates :name, length: { maximum: 255 }

  belongs_to :user
  belongs_to :event, optional: true

  has_many :likes, dependent: :destroy
  has_many :materials

  scope :ordered,  -> { order('created_at DESC') }
  scope :undone,   -> { where('event_id IS NULL') }
  scope :done,     -> { joins(:event).where('date <= ?', Time.now - 2.hours) }
  scope :upcoming, -> { joins(:event).where('date > ?', Time.now - 2.hours) }

  default_scope -> { where(label: Whitelabel[:label_id]) }

  def already_liked?(user)
    likes.detect { |like| like.user == user }
  end
end

app/controllers/admin/topics_controller.rb
module Admin
  class TopicsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Topic.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Topic.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/super_admin/topics_controller.rb
module SuperAdmin
  class TopicsController < SuperAdmin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Topic.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Topic.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/topics_controller.rb
# frozen_string_literal: true

class TopicsController < ApplicationController
  before_action :authenticate!, only: %i[new edit update create]
  before_action :validate_topic_ownership!, only: %i[edit update]

  expose(:topic, find: ->(id, scope) { scope.from_slug(id) })
  expose(:events)           { Event.with_topics.ordered.page(params[:page]) }
  expose(:undone_topics)    { Topic.ordered.undone }
  expose(:done_topics)      { Topic.ordered.done }
  expose(:upcoming_topics)  { Topic.ordered.upcoming }

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    topic.label = Whitelabel[:label_id]
    topic.user  = current_user
    topic.assign_attributes(topic_params)
    if topic.save
      if current_user.email.blank?
        redirect_to(edit_user_path(current_user), notice: t('flash.add_email'))
      else
        redirect_to(topic_path(topic), notice: t('flash.topic_added'))
      end
    else
      redirect_to(new_topic_path, alert: topic.errors.full_messages.join(', '))
    end
  end

  def update
    if topic.update(topic_params)
      redirect_to(topic_path(topic), notice: t('flash.topic_updated'))
    else
      redirect_to(edit_topic_path, alert: topic.errors.full_messages.join(', '))
    end
  end

  private

  def validate_topic_ownership!
    redirect_to(root_path, alert: t('flash.not_authenticated')) if topic.user != current_user && !current_user.admin?
  end

  def topic_params
    params.require(:topic).permit(:label, :name, :user, :description, :proposal_type)
  end
end

app/helpers/topics_helper.rb
# frozen_string_literal: true

module TopicsHelper
  def like_link(topic)
    if signed_in?
      if topic.user == current_user
        button_to t('topic.edit'), edit_topic_path(topic), method: :get, class: 'btn btn-primary'
      elsif like = topic.already_liked?(current_user)
        button_to t('topic.unlike'), topic_like_path(like.topic, like), method: :delete, class: 'btn btn-primary'
      else
        button_to t('topic.like'), topic_likes_path(topic), method: :post, class: 'btn btn-primary'
      end
    else
      button_to t('topic.like'), login_path, method: :get, params: { origin: request.path }, class: 'btn btn-primary'
    end
  end

  def proposal_type_selection
    Topic::PROPOSAL_TYPES.index_by { |type| I18n.t("topic.proposal_types.#{type}") }
  end
end

app/views/topics/_done.slim
- if topics.present?
  #done
    h3= t('home.old_topics')
    ul.more-list.clearfix
      - topics.each do |topic|
        li.topic
          = link_to_topic topic
      li.all= fa_icon 'mail-forward', text: link_to(t('topic.all_topics'), topics_path)

app/views/topics/_form.slim
= simple_form_for topic do |f|
  = f.input :name
  = f.input :proposal_type, as: :select, include_blank: false, collection: proposal_type_selection
  p.info== t("topic.markdown")
  = f.input :description
  = f.button :submit, class: 'btn-primary'

app/views/topics/_likes.slim
- if topic.likes.present?
  h3= t 'topic.likes', count: topic.likes.size
  ul
    - topic.likes.each do |like|
      li
        = fa_icon 'thumbs-o-up', class: 'pull-left'
        = link_to_user like.user

app/views/topics/_materials.slim
- if materials.present?
  h3#materials= t("main.materials")
  ul
    - materials.each do |material|
      li
        = link_to_material(material)
        == " (#{link_to_user(material.user)})" if material.user
        = material_preview(material)

app/views/topics/_undone.slim
#undone
  h3= t("home.new_topics")
  - if topics.present?
    ul.more-list.undone.clearfix
      - topics.each do |topic|
        li.topic
          = link_to_topic topic
  - else
    p== t("home.no_new_topics", new_topic_link: link_to(t('topic.topic'), new_topic_path))

app/views/topics/_upcoming.slim
- if topics.present?
  #upcoming
    h3= t('home.upcoming_topics')
    ul.more-list.clearfix
      - topics.each do |topic|
        li.topic
          = link_to_topic topic

app/views/topics/edit.slim
= section_box :topics do
  p.info== t("topic.markdown")
  p= render 'form', topic: topic
  = render 'undone', topics: undone_topics

app/views/topics/index.slim
= section_box :topics do
  - events.each do |event|
    p
      strong= link_to_event event
      = " (#{l(event.date, format: :date)})"
    ul.more-list.undone.clearfix
    - event.topics.each do |topic|
      li.topic= link_to_topic topic
  = paginate events

app/views/topics/new.slim
= section_box :topics do
  p.info== t("topic.markdown")
  p= render 'form', topic: topic

  = render 'undone', topics: undone_topics

app/views/topics/show.mobile.slim
h2= topic.name

== markdown topic.description

app/views/topics/show.slim
.card
  .card-header
    == t("topic.proposal_type_descriptions.#{topic.proposal_type}", user: link_to_user(topic.user, image: true))

  .card-body
    h2.card-title= topic.name
    p.card-text== markdown(topic.description)

  .card-body
    = like_link(topic)

  .card-body.row
    - if topic.materials.present?
      .col-sm
        h3.card-title= t("main.materials")
        ul.list-group.list-group-flush
          - topic.materials.each do |material|
            li.list-group-item
              = link_to_material(material)
              == " (#{link_to_user(material.user)})" if material.user
              = material_preview(material)

    - if topic.likes.present?
      .col-sm
        h3.card-title= t('topic.likes', count: topic.likes.size)
        ul.list-group.list-group-flush
          - topic.likes.each do |like|
            li.list-group-item
              = fa_icon('thumbs-o-up', class: 'pull-left', text: link_to_user(like.user))

  - if topic.event.present?
    .card-footer== t("topic.hosted_by", host: link_to_user(topic.event.user), event: link_to(topic.event.name, topic.event))