config/routes.rb
OnRuby::Application.routes.draw do
  namespace :admin do
    resources :events do
      post :duplicate, on: :collection
      post :connect, on: :member
    end
    resources :locations
    resources :topics
    resources :materials
    resources :highlights
    resources :jobs
    resources :users

    root to: 'events#index'
  end
  namespace :super_admin do
    resources :events do
      post :duplicate, on: :collection
      post :connect, on: :member
    end
    resources :locations
    resources :topics
    resources :materials
    resources :highlights
    resources :jobs
    resources :authorizations
    resources :likes
    resources :participants
    resources :users

    root to: 'events#index'
  end

  get 'image/:timestamp/:model_name/:model_id/*filename' => 'images#show', as: :image_dispatch

  resource :sitemap, only: :show

  resources :users do
    get :calendar, on: :member
  end

  resources :locations do
    get :none, on: :collection
  end

  resources :events do
    resources :materials
    resources :topics
    resources :participants
  end

  resources :topics do
    resources :likes
  end

  scope '/auth' do
    get '/',                         to: 'sessions#index', as: :login
    get '/:provider/callback',       to: 'sessions#create', as: :provider_callback
    get '/failure',                  to: 'sessions#failure'
    get '/destroy_session',          to: 'sessions#destroy', as: :destroy_session
    get '/offline_login/:nickname',  to: 'sessions#offline_login' if Rails.env.development?
  end

  scope "/sessions" do
    get "/email", to: "sessions#email"
    post "/email_login", to: "sessions#email_login"
  end

  constraints MainDomainConstraint.new do
    get '/', to: 'labels#index', as: :labels
  end

  scope '/api' do
    get '/', to: 'api#index', as: :api
    get '/flush', to: 'api#flush', as: :flush
  end

  root to: 'home#index'

  match '*path.php', via: :all, to: ->(_env) { [301, { 'Location' => 'http://www.youporn.com/' }, ['fuck yourself!']] }
  match '*path', via: :all, constraints: ->(request) { request.path !~ %r{\A/admin} }, to: ->(_env) { [404, { 'Content-Type' => 'text/html' }, ['not found']] }
end

app/views/shared/_footer.html.haml
%section.clearfix
  #contact.block
    %h2= t("footer.contact")
    %ul
      %li
        = link_to_twitter Whitelabel[:twitter] do
          = "Twitter"
      %li= mail_to Whitelabel[:email], 'E-Mail'

  #links.block
    %h2= t("footer.links")
    %ul
      %li= link_to 'Github', 'http://github.com/phoet/on_ruby'
      %li= link_to 'Mailinglist', (Whitelabel[:mailing_list] || 'https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-ug-germany')
  #imprint.block
    %h2= t("footer.imprint")
    %ul
      %li
        - imprint[:contributors].each do |contributor|
          = mail_to contributor[:email], contributor[:name]
      - if imprint[:address]
        %li= raw imprint[:address].gsub("\n", "<br/>")

  - if other_usergroups.present?
    #usergroups.block
      %h2= t("footer.other_usergroups")
      %ol.clearfix
        - other_usergroups.each do |ug|
          %li
            = link_to ug[:name], ug[:url]
            = link_to_twitter(ug[:twitter], clung: true) if ug[:twitter]

  #railsgroups.block
    %h2= t("footer.ruby_usergroups")
    %ol.clearfix
      - Whitelabel.labels.each do |label|
        %li
          = link_to t("label.#{label.label_id}.name"), "http://#{label.label_id}.onruby.de"
          = link_to_twitter(label.twitter, clung: true)

app/views/shared/_footer.html.slim
section.clearfix
  .info.clearfix.hr
    .contact.block
      h2= t("footer.contact")
      ul
        li
          = link_to_twitter Whitelabel[:twitter] do
            = "Twitter"
        li= mail_to Whitelabel[:email], 'E-Mail', title: "#{Whitelabel[:twitter]} E-Mail"

    .links.block
      h2= t("footer.links")
      ul
        li= link_to 'GitHub', 'http://github.com/phoet/on_ruby', title: 'Fork me on GitHub'
        li= link_to 'Mailinglist', mailing_list_url, title: 'Mailinglist'

    .imprint.block
      h2= t("footer.imprint")
      ul
        li== imprint[:contributors].map { |c| mail_to c[:email], c[:name], title: c[:name] }.join(' ')
        - if imprint[:address]
          li== simple_format imprint[:address]

  - if other_usergroups.present?
    .usergroups.block.hr
      h2= I18n.tw("footer.other_usergroups")
      ol.clearfix
        - other_usergroups.each do |ug|
          li
            =' link_to ug[:name], ug[:url], title: ug[:name]
            = link_to_twitter(ug[:twitter], clung: true) if ug[:twitter]

  .railsgroups.block.hr
    h2= t("footer.ruby_usergroups")
    ol.clearfix
      - Whitelabel.labels.each do |label|
        li
          - name = t("label.#{label.label_id}.name")
          =' link_to name, root_url(subdomain: label.label_id, domain: HOST), title: name
          = link_to_twitter(label.twitter, clung: true)

  .railssupporters.block
    h2= t("footer.ruby_supporters")
    ol.clearfix
      li= link_to "Ruby Berlin e.V.", "http://rubyberlin.org/"

app/views/shared/_hint.html.haml
- if flash.present?
  = hint do
    - flash.each do |key, value|
      %strong{class: key}= value
- elsif highlights.present?
  #highlights
    = hint(false) do
      - highlights.each do |highlight|
        .highlights
          %strong= t("hint.attention")
          = link_to highlight.description, highlight.url, title: highlight.description
- elsif jobs.present?
  - unless current_user && current_user.hide_jobs?
    #jobs
      = hint(false) do
        .reload= link_to t("hint.other_job"), '#'
        - jobs.each do |job|
          .jobs= raw t("hint.job_description", city: I18n.tw("city"), job_link: content_tag(:strong, link_to(job.name, job.url, title: job.name)), company_link: link_to(job.location.name, job.location.url, title: job.location.name))

app/views/shared/_hint.html.slim
- if flash.present?
  = hint do
    - flash.each do |key, value|
      strong(class=key)= value
- else
  - if highlights.present?
    - render_cached(:highlights) do
      #highlights
        = hint(false) do
          - highlights.each do |highlight|
            .highlights
              strong=' t("hint.attention")
              = link_to highlight.description, highlight.url, title: highlight.description
  - elsif jobs.present?
    - unless current_user && current_user.hide_jobs?
      - render_cached(:jobs) do
        #jobs
          = hint(false) do
            span.reload= link_to fa_icon("refresh"), '#', title: 'click me to refresh!'
            - jobs.each do |job|
              .jobs== job_description(job)

app/views/shared/_hint.slim
- if flash.present?
  = hint do
    - flash.each do |key, value|
      strong(class=key)= value
- else
  - if highlights.present?
    - render_cached(:highlights) do
      #highlights
        = hint(false) do
          - highlights.each do |highlight|
            .highlights
              strong=> t("hint.attention")
              = link_to highlight.description, highlight.url, title: highlight.description
  - elsif jobs.present? && (request.original_fullpath != root_path)
    - unless current_user && current_user.hide_jobs?
      - render_cached(:jobs) do
        = hint(false) do
          #job-teaser
            span.job-toggle= link_to fa_icon("chevron-down"), '#', title: t("hint.click_to_refresh")
            .job== job_description(jobs.first)
          #job-list.hidden
            ul
              - jobs.each_with_index do |job, index|
                li
                  span.job-toggle= link_to fa_icon("chevron-up"), '#', title: t("hint.click_to_refresh") if index == 0
                  .job== job_description(job)

app/views/shared/_info.html.slim
| <!-- ruby-#{RUBY_VERSION}-#{RUBY_PATCHLEVEL} on rails-#{Rails.version} served by unicorn-#{Unicorn::Const::UNICORN_VERSION} -->

app/views/shared/_info.slim
| <!-- Ruby-#{RUBY_VERSION}-#{RUBY_PATCHLEVEL} on Rails-#{Rails.version} in env #{Rails.env} -->
- if ENV['MY_SHA_REVISION'].present?
  | <!-- Git-#{{ENV['MY_SHA_REVISION']}} -->
- if defined?(Puma)
  | <!-- served by Puma-#{Puma::Const::PUMA_VERSION} #{Puma::Const::CODE_NAME} -->

app/views/shared/_nav.html.haml
%ul
  %li
    = link_to root_path(anchor: "on_ruby"), title: title do
      %p.logo.ir= title
  - [:events, :people, :locations, :wishes, :companies].each do |it|
    %li= link_to t(it), root_path(anchor: it), title: t(it)
  %li
    = link_to root_path(anchor: "on_ruby"), title: title do
      %p.logo.ir= title

#locale
  %ul
    -[:de, :en].each do |locale|
      %li= link_to image_tag("flags/#{locale}.png"), locale: locale

app/views/shared/_nav.html.slim
nav#nav.navbar
  = render 'peek/bar'
  .nav-box
    ul.nav-inner
      - nav_entries = [:events, :topics, :people, :mailing_list, :locations]
      li.label
        = link_to image_tag("labels/#{Whitelabel[:label_id]}.png", class: 'label-img', alt: title), '#on_ruby', class: 'label-link'
      - nav_entries.each do |it|
        li
          = link_to root_path(anchor: it), title: t(it) do
            i class="icon icon-#{it}"
            span.nav-text.hide-phone= t(it)
      li.menu-button
        .nav-toggle.toggle(name="sub-nav-box")
          i class="icon icon-bars"

    .sub-nav-box.toggle_sub-nav-box
      ul.nav-sub
        - if signed_in?
          li.userimage= link_to image_tag(current_user.image, alt: current_user.name), user_path(current_user), title: current_user.name
          li
            = link_to edit_user_path(current_user), title: t("login.edit_profile") do
              = fa_stacked_icon 'edit', base: "square-o"
              =' t("login.edit_profile")
          li
            = link_to destroy_session_path(current_user), title: t("login.logout") do
              = fa_stacked_icon 'times', base: "square-o"
              =' t("login.logout")
        - else
          - [:twitter, :github].each do |provider|
            - title = t("login.#{provider}_login")
            li.provider
              = link_to auth_path(provider: provider), title: title do
                = fa_stacked_icon provider, base: "square-o"
                =' title
        - locale = I18n.locale == :de ? :en : :de
        - title = t("languages.#{locale}")
        li.locale
          = link_to url_for(locale: locale), title: t("switch_languages", language: title) do
            = fa_stacked_icon 'comment', base: "square-o"
            =' title

app/views/shared/_participate_button.html.haml
%span
  -if current_user
    - if current_user.participates?(@event)
      = link_to current_user.participation(@event), {:method => :delete, :class => :button, :title => 'abmelden'} do
        =image_tag('minus.png', :title => 'abmelden', :alt => 'abmelden')
    -else
      = link_to(add_user_participant_path(@event.id), {:class => :button, :title => 'teilnehmen'}) do
        =image_tag('plus.png', :title => 'teilnehmen', :alt => 'teilnehmen')
  - else
    =link_to(auth_path, :class => :button, :title => 'teilnehmen') do
      =image_tag('plus.png', :title => 'teilnehmen', :alt => 'teilnehmen')

app/views/shared/_route.html.slim
h3#route= t("show.route")
= single_map(location)
= link_to_external_route(location)

app/views/shared/_script.html.slim
- if Rails.env.production?
  javascript:
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-20148095-1']);
    _gaq.push(['_setDomainName', 'onruby.de']);
    _gaq.push(['_setAllowLinker', true]);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

app/views/shared/_show_flash.haml
- if flash.present?
  = hint do
    - flash.each do |key, value|
      %strong{class: key}= value

app/views/shared/_users.html.haml
/     TODO remove the rand and the * 10 from the users
%ul.imagelist.clearfix
  - (users * 10).each do |user|
    %li.tooltip
      - uid = rand(200) + user.id + rand(200)
      = image_tag user.image, class: 'toggle', name: uid
      %div{class: "toggle_#{uid}"}
        %h3= user.name
        %dl
          %dt Twitter:
          %dd= link_to_twitter user
          - if user.github
            %dt Github:
            %dd= link_to_github user