config/routes.rb
OnRuby::Application.routes.draw do
  namespace :admin do
    resources :events do
      post :duplicate, on: :collection
      post :connect, on: :member
    end
    resources :locations
    resources :topics
    resources :materials
    resources :highlights
    resources :jobs
    resources :users

    root to: 'events#index'
  end
  namespace :super_admin do
    resources :events do
      post :duplicate, on: :collection
      post :connect, on: :member
    end
    resources :locations
    resources :topics
    resources :materials
    resources :highlights
    resources :jobs
    resources :authorizations
    resources :likes
    resources :participants
    resources :users

    root to: 'events#index'
  end

  get 'image/:timestamp/:model_name/:model_id/*filename' => 'images#show', as: :image_dispatch

  resource :sitemap, only: :show

  resources :users do
    get :calendar, on: :member
  end

  resources :locations do
    get :none, on: :collection
  end

  resources :events do
    resources :materials
    resources :topics
    resources :participants
  end

  resources :topics do
    resources :likes
  end

  scope '/auth' do
    get '/',                         to: 'sessions#index', as: :login
    get '/:provider/callback',       to: 'sessions#create', as: :provider_callback
    get '/failure',                  to: 'sessions#failure'
    get '/destroy_session',          to: 'sessions#destroy', as: :destroy_session
    get '/offline_login/:nickname',  to: 'sessions#offline_login' if Rails.env.development?
  end

  scope "/sessions" do
    get "/email", to: "sessions#email"
    post "/email_login", to: "sessions#email_login"
  end

  constraints MainDomainConstraint.new do
    get '/', to: 'labels#index', as: :labels
  end

  scope '/api' do
    get '/', to: 'api#index', as: :api
    get '/flush', to: 'api#flush', as: :flush
  end

  root to: 'home#index'

  match '*path.php', via: :all, to: ->(_env) { [301, { 'Location' => 'http://www.youporn.com/' }, ['fuck yourself!']] }
  match '*path', via: :all, constraints: ->(request) { request.path !~ %r{\A/admin} }, to: ->(_env) { [404, { 'Content-Type' => 'text/html' }, ['not found']] }
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  expose(:current_event)    { Event.current.first }
  expose(:events)           { Event.latest.limit(10) }
  expose(:people)           { User.peers.limit(3 * 5) }
  expose(:undone_topics)    { Topic.ordered.undone }
  expose(:upcoming_topics)  { Topic.ordered.upcoming }
  expose(:done_topics)      { Topic.ordered.done.limit(10) }
  expose(:organizers)       { User.organizers }
  expose(:locations)        { Location.joins(:events).merge(Event.where(date: (2.years.ago.beginning_of_year)..)).distinct }
  expose(:zoom)             { Whitelabel[:location][:zoom] }

  def index; end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
  def next_event_date
    l(Whitelabel[:next_event_date], format: :long)
  end

  def localized_recurring_event_date
    Whitelabel[:localized_recurring]
  end

  def contact_text
    capture do
      concat t('home.send_us_an_email', mail_to: mail_to(Whitelabel[:email], 'E-Mail', title: 'E-Mail')).html_safe
      concat " #{t('home.or_message_on_twitter', twitter_link: link_to_twitter(Whitelabel[:twitter]))}".html_safe if Whitelabel[:twitter]
      concat '.'
    end
  end

  def header_image_path
    File.join('labels', Whitelabel[:label_id], 'header.png')
  end

  def header_image_available?
    Rails.root.join('app', 'assets', 'images', header_image_path).exist?
  end
end

app/views/home/_featured.slim
- if current_event.present?
  .card
    .card-header
      = render('events/badges', event: current_event)

    .card-body
      = render('events/info', event: current_event)
      = render('events/topics', event: current_event)
      = render('events/participants', event: current_event)
      = render('events/location', event: current_event)

app/views/home/_locations.html.slim
= section_box :locations do
  = map(locations)
  - options = { location_link: link_to(t("locations"), locations_path, title: t("locations")) }
  p== t("home.usergroup_locations", options)
  p== t("home.company_workers")
  - options = { email_link: mail_to(Whitelabel[:email], "E-Mail", title: "E-Mail"), twitter_link: link_to_twitter(Whitelabel[:twitter]) }
  p== t("home.company_missing", options)

app/views/home/_people.html.haml
= section_box :people do
  %p= raw t("home.the_usergroup", usergroup: I18n.tw("name"))
  = render 'users_list', users: people

app/views/home/_people.html.slim
= section_box :people do
  p== t("home.the_usergroup", usergroup: I18n.tw("name"))
  = render 'users/list', users: people

app/views/home/_people.slim
= section_box :people do
  = slackin_js
  p== I18n.tw("home.the_usergroup", usergroup: I18n.tw("name"))
  = render 'users/list', users: people
  = fa_icon 'mail-forward', text: link_to(t('home.all_people'), users_path)

app/views/home/_users_list.html.slim
.imagelist
  ul
    - users.compact.each do |user|
      li
        = link_to user, title: user.name do
          = image_tag 'logo.png', alt: user.name, 'data-src' => user.image

app/views/home/_users_list.slim
.imagelist
  ul
    - users.each do |user|
      li
        = link_to user, title: user.name do
          = image_tag 'logo.png', alt: user.name, data: {src: user.image}

app/views/home/_wishes.html.haml
= section_box :wishes do
  %p
    %strong= t("home.like_to_talk")
    = raw t("home.send_us_an_email", mail_to: Whitelabel[:email])
  %ul
    = render 'users_list', users: organizers
  %p= raw t("home.engage")
  %p
    = submit_tag t("home.add_topic"), name: 'new_wish', class: 'toggle'
    .toggle_new_wish.hidden
      %p
        = semantic_form_for Wish.new do |f|
          = f.input :name
          = f.input :description
          = f.action(:submit)
  - if wishes_undone.present?
    #undone
      %h3= t("home.new_topics")
      %ul.undone.clearfix
        - wishes_undone.each do |wish|
          %li
            %span.stars= stars(wish)
            = link_to wish.name, wish, title: wish.name
  - if wishes_done.present?
    #done
      %h3= t("home.old_topics")
      %ul.clearfix
        - wishes_done.each do |wish|
          %li
            %span.stars= stars(wish)
            = link_to wish.name, wish, title: wish.name

app/views/home/_wishes.html.slim
= section_box :wishes do
  p
    strong=' t("home.like_to_talk")
    == t("home.send_us_an_email", mail_to: mail_to(Whitelabel[:email], "E-Mail", title: "E-Mail"))
  = render 'users/list', users: organizers
  p== t("home.engage")
  = button_to t("home.add_topic"), new_wish_path, method: :get
  = render 'wishes/undone', wishes: wishes_undone
  = render 'wishes/done', wishes: wishes_done

app/views/home/index.html.haml
= render 'events', events: events, current_event: current_event
= render 'people', people: people
= render 'locations', locations: locations
= render 'wishes', wishes_done: wishes_done, wishes_undone: wishes_undone, organizers: organizers
= render 'companies', companies: companies

app/views/home/index.slim
= render 'featured', current_event: current_event
= render 'events', events: events, current_event: current_event
= render 'topics', undone_topics: undone_topics, done_topics: done_topics, upcoming_topics: upcoming_topics, organizers: organizers
= render 'people', people: people
= render 'locations', locations: locations

app/views/home/labels.haml
= section_box :usergroups do
  %ul
    - Whitelabel.labels.each do |label|
      %li
        = link_to root_url(subdomain: label.label_id) do
          .whitelabel
            = image_tag("labels/#{label.label_id}.png")
            = label.host

app/views/home/labels.mobile.slim
ul data-role="listview"
  - Whitelabel.labels.each do |label|
    li
      = link_to label.host, root_url(subdomain: label.label_id)

app/views/home/labels.slim
section
  ul
    - Whitelabel.labels.each do |label|
      li
        - name = t("label.#{label.label_id}.name")
        = link_to root_url(subdomain: label.label_id, domain: TLD), title: name do
          span.image = image_tag("labels/#{label.label_id}.png", alt: name)
          span.host  = name