config/routes.rb
OnRuby::Application.routes.draw do
  namespace :admin do
    resources :events do
      post :duplicate, on: :collection
      post :connect, on: :member
    end
    resources :locations
    resources :topics
    resources :materials
    resources :highlights
    resources :jobs
    resources :users

    root to: 'events#index'
  end
  namespace :super_admin do
    resources :events do
      post :duplicate, on: :collection
      post :connect, on: :member
    end
    resources :locations
    resources :topics
    resources :materials
    resources :highlights
    resources :jobs
    resources :authorizations
    resources :likes
    resources :participants
    resources :users

    root to: 'events#index'
  end

  get 'image/:timestamp/:model_name/:model_id/*filename' => 'images#show', as: :image_dispatch

  resource :sitemap, only: :show

  resources :users do
    get :calendar, on: :member
  end

  resources :locations do
    get :none, on: :collection
  end

  resources :events do
    resources :materials
    resources :topics
    resources :participants
  end

  resources :topics do
    resources :likes
  end

  scope '/auth' do
    get '/',                         to: 'sessions#index', as: :login
    get '/:provider/callback',       to: 'sessions#create', as: :provider_callback
    get '/failure',                  to: 'sessions#failure'
    get '/destroy_session',          to: 'sessions#destroy', as: :destroy_session
    get '/offline_login/:nickname',  to: 'sessions#offline_login' if Rails.env.development?
  end

  scope "/sessions" do
    get "/email", to: "sessions#email"
    post "/email_login", to: "sessions#email_login"
  end

  constraints MainDomainConstraint.new do
    get '/', to: 'labels#index', as: :labels
  end

  scope '/api' do
    get '/', to: 'api#index', as: :api
    get '/flush', to: 'api#flush', as: :flush
  end

  root to: 'home#index'

  match '*path.php', via: :all, to: ->(_env) { [301, { 'Location' => 'http://www.youporn.com/' }, ['fuck yourself!']] }
  match '*path', via: :all, constraints: ->(request) { request.path !~ %r{\A/admin} }, to: ->(_env) { [404, { 'Content-Type' => 'text/html' }, ['not found']] }
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  include Slug
  extend ApiHandling
  expose_api :id, :name, :description, :date, :location_id, :user_id, :participants, :topics, :materials, :location

  belongs_to :location, optional: true
  belongs_to :user

  has_many :participants
  has_many :users, through: :participants
  has_many :topics
  has_many :materials

  validates :user, :name, :description, :date, presence: true
  validates :name, uniqueness: { scope: :label }

  accepts_nested_attributes_for :materials
  accepts_nested_attributes_for :topics

  default_scope       -> { where(label: Whitelabel[:label_id]) }

  scope :with_topics, -> { joins(:topics).distinct }
  scope :current,     -> { where(date: Date.today.to_time..).limit(1).order(date: :asc) }
  scope :latest,      -> { where('date < ?', Date.today.to_time).order(date: :desc) }
  scope :unpublished, -> { where('published IS NULL') }
  scope :ordered,     -> { order(date: :desc) }

  def end_date
    date + 2.hours
  end

  def closed?
    limit.present? && participants.count >= limit
  end

  def particpate(user)
    return false if users.include? user

    !!participants.create!(user:)
  end

  class << self
    def duplicate!
      latest  = Event.last
      date    = Whitelabel[:next_event_date]
      Event.new.tap do |it|
        it.name         = "#{I18n.tw('name')} - #{I18n.l date, locale: :de, format: :month}"
        it.date         = date
        it.user         = latest.user
        it.location     = latest.location
        it.description  = latest.description
        it.save!
      end
    end

    def stats(size: 10)
      stats = Event.limit(size).map { |event| [event.participants.count, event.topics.count] }
      {
        participants: stats.empty? ? 0 : stats.map(&:first).sum / stats.size,
        topics: stats.empty? ? 0 : stats.map(&:last).sum / stats.size,
      }
    end
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::ApplicationController
    def duplicate
      event = Event.duplicate!

      redirect_to [:edit, :admin, event], notice: 'Event duplicated!'
    end

    def connect
      event = find_resource(params[:id])
      topic = Topic.undone.find(params[:topic_id])
      topic.update! event: event
      event.particpate(topic.user)

      redirect_to [:admin, event], notice: 'Connected to Event!'
    end

    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Event.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Event.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  include IcalHelper

  expose(:events) { Event.ordered.page(params[:page]) }
  expose(:event)  { Event.includes(materials: :user, topics: :user, participants: :user).from_param(params[:id]) }

  def index
    respond_to do |format|
      format.html
      format.xml  { render layout: false }
      format.json { render json: events.as_api_response(:ios_v1) }
      format.ics  { render plain: icalendar(*events) }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json do
        render json: event.as_api_response(:ios_v1)
      end
      format.ics do
        render plain: icalendar(event)
      end
    end
  end
end

app/controllers/super_admin/events_controller.rb
module SuperAdmin
  class EventsController < SuperAdmin::ApplicationController
    def duplicate
      event = Event.duplicate!

      redirect_to [:edit, :admin, event], notice: 'Event duplicated!'
    end

    def connect
      event = find_resource(params[:id])
      topic = Topic.undone.find(params[:topic_id])
      topic.update! event: event
      event.particpate(topic.user)

      redirect_to [:admin, event], notice: 'Connected to Event!'
    end

    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Event.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Event.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def participation_link(event, link_class: 'btn btn-primary')
    if signed_in?
      if current_user.participates?(event)
        link_to t('show.not_attend'), [event, current_user.participation(event)], method: :delete, class: link_class
      elsif event.closed?
        link_to t('show.attend'), '#', data: { disable: t('flash.already_closed') }, class: link_class
      else
        link_to t('show.attend'), [event, Participant.new], method: :post, class: link_class
      end
    else
      link_to t('show.attend'), login_path, params: { origin: request.path }, class: link_class
    end
  end

  def all_events_webcal_link
    fa_icon('calendar', text: link_to(t('events.webcal'), events_url(format: :ics, protocol: 'webcal')))
  end

  def all_events_rss_link
    fa_icon('rss', text: link_to(t('events.rss'), events_url(format: :xml)))
  end

  def events_im_attending_link
    fa_icon('calendar', text: link_to(t('events.webcal'), calendar_user_url(id: current_user, format: :ics, protocol: 'webcal')))
  end

  def remote_url_link(event, link_class: 'btn btn-primary')
    return unless signed_in? && current_user.participates?(event) && event.remote_url.present?

    link_to t('events.connect_remotely'), event.remote_url, class: link_class
  end
end

app/views/events/_badge.html.erb
<div class="rounded-full border-secondary bg-primary p-2 text-white text-xs flex">
  <%= yield %>
</div>

app/views/events/_badges.slim
span.badge.badge-card-header.me-2
  = fa_icon('calendar', text: link_to(l(event.date, format: :long), event_path(event, format: :ics)))
- if event.location.present? && !event.location.virtual?
  span.badge.badge-card-header.me-2
    = fa_icon('map-marker', text: link_to(event.location.address, '#route', title: event.location.address))
  span.badge.badge-card-header.me-2
    = fa_icon('external-link', text: link_to_external_route(event.location))
- if Whitelabel[:coc].present?
  span.badge.badge-card-header.me-2
    = fa_icon('file-text-o', text: link_to('Code of Conduct', Whitelabel[:coc], target: '_blank'))
- if event.github_issue?
  span.badge.badge-card-header.me-2
    = fa_icon('github', text: link_to('Github Planning Issue', github_issue_url(event.github_issue), target: '_blank'))

app/views/events/_info.slim
.d-flex.card-title
  .flex-fill
    h2= link_to_event(event)
    small.text-muted
      = t("show.hosted_by")
      =< link_to_user(event.user)
      - if event.location.present?
        =< t('show.at')
        =< link_to_location(event.location)
      = ", #{l(event.date, format: :long)}"

  div
    = participation_link(event, link_class: 'btn btn-primary btn-block')
    = remote_url_link(event, link_class: 'btn btn-primary btn-block')

.card-text
  == markdown(event.description)

- if event.attendee_information?
  - if signed_in?
    .card-text
      == markdown(event.attendee_information)
  - else
    .card-text
      mark= t('show.attend_to_view_attendees_information')

app/views/events/_live.html.erb
<%= render('events/badge') do %>
  <span class="rounded-full bg-white h-4 w-4 mr-1 flex items-center justify-center">
    <span class="rounded-full bg-primary h-3 w-3 flex items-center justify-center">
      <span class="rounded-full bg-white h-1 w-1 flex items-center justify-center"></span>
    </span>
  </span>
  Live Now
<% end %>

app/views/events/_location.slim
- if event.location.present? && !event.location.virtual?
    h3.card-title
      = t("show.route")
      - if event.location.wheelmap_id?
        .pull-right
          = wheelmap_badge(event.location)

    #route= single_map(event.location)

app/views/events/_materials.slim
- if materials.present?
  h3.card-title#materials= t("main.materials")
  ul
    - materials.each do |material|
      li
        = link_to_material(material)
        == " (#{link_to_user(material.user)})" if material.user
        = material_preview(material)

app/views/events/_part.haml
- parts = event.send(type)
- if parts.present?
  %h3= t("#{type}")
  %ul.enumeration
    - parts.each do |p|
      %li
        = p.respond_to?(:url) ? link_to(p.name, p.url) : p.name
        - if p.user
          = link_to_twitter(p.user, clung: true)
        %p= simple_format p.description

app/views/events/_participants.slim
- if event.participants.present?
  h3.card-title= t("show.attendees", count: event.limit || 0, participant_count: event.participants.count)
  p= render 'users/list', users: event.users

app/views/events/_topics.slim
- if event.topics.present?
  h3.card-title= t("main.topics")

  .row.row-cols-1.row-cols-md-2.g-4
    - event.topics.each do |topic|
      .col
        .card.h-100
          .card-header
            .pull-left
              = link_to(topic.user) do
                = user_image(topic.user, image_class: 'card-img-topic-header')
            = link_to_user(topic.user)
          .card-body
            h5.card-title= link_to_topic(topic)
            .card-text.collapser== markdown(topic.description)
          - if topic.materials.present?
            ul.list-group.list-group-flush
              - topic.materials.each do |material|
                li.list-group-item= link_to_material(material)
          .card-footer
            small.text-muted
              = link_to t('topic.likes', count: topic.likes.count), topic

app/views/events/index.slim
= section_box :events do
  - events.each do |event|
    p
      strong= link_to_event event
      = " (#{l(event.date, format: :date)})"
    ul.more-list.undone.clearfix
      - event.topics.each do |topic|
        li.topic= link_to_topic topic
  = paginate events

  p.meta
    - if signed_in?
      span.pull-right
        = t('events.im_attending_html', events_im_attending_link: events_im_attending_link)

    = t 'events.calendar_html',
      webcal_link: all_events_webcal_link,
      rss_link:    all_events_rss_link

app/views/events/show.html.erb
<% content_for(:page_title, event.name) %>

<div class="block group border border-b-0 rounded rounded-b-none border-gray-200 bg-gray-100 p-0 h-60" style="background: url(<%= event.image_url %>)  no-repeat center center fixed">
  <div class="float-left m-2">
    <%= render('events/live') %>
  </div>
  <div class="float-right m-2">
    <%= render('events/badge') %>
  </div>
</div>
<div class="block group border border-t-0 rounded rounded-t-none border-gray-200 bg-white p-3">
  <div class="grid grid-cols-3">
    <div class="flex">
      <div>
        <div class="m-3 rounded-full border-primary bg-gray-100 p-2 text-secondary text-xs">
          👩‍💻 Online
        </div>
      </div>
      <div>
        <div class="m-3 rounded-full border-primary bg-gray-100 p-2 text-secondary text-xs">
          👾 Wonder
        </div>
      </div>
    </div>
    <div class="flex m-3">
      hosted by <%= link_to(user_image(event.user, image_class: 'rounded-full mx-2 bg-primary w-6 h-6'), event.user) %>
      at <%= link_to(event.location.name, event.location, class: 'mx-2 underline') %>
    </div>
    <div class="flex">
      <%= participation_link(event, link_class: 'flex-grow m-3 rounded-full border-4 border-primary bg-gray-100 p-2 text-secondary text-center text-xs font-bold') %>
    </div>
  </div>
  <div>
    <div class="p-3">
      <h2 class="text-xl"><%= event.name %></h2>
      <div class="">
        <%= markdown(event.description) %>
      </div>
    </div>
    <div class="p-3">
    </div>
    <% if event.topics.present? %>
      <h3>Speaker</h3>
      <div class="grid grid-cols-1 gap-y-8 sm:grid-cols-2 sm:gap-x-5 sm:gap-y-6 md:grid-cols-3 lg:col-span-3">
        <% event.topics.each do |topic| %>
        <div class="block group border rounded border-gray-200 bg-gray-100 p-3">
          <figure class="grid grid-cols-1 gap-y-8 grid-cols-2">
            <div class="relative p-3">
              <%= link_to(user_image(topic.user, image_class: 'rounded-full border-primary bg-gray-100 h-20'), topic.user) %>
            </div>
            <figcaption class="mt-3">
              <p class="text-sm font-medium text-gray-900"><%= user.name %></p>
              <p class="text-sm text-gray-500"><%= topic.name %></p>
            </figcaption>
          </figure>
        </div>
        <% end %>
      </div>
    <% end %>

    <% if event.users.present? %>
      <h3><strong>Members</strong> registered</h3>
      <div class="flex flex-wrap">
        <% event.users.each do |user| %>
        <div class="m-3">
          <%= link_to(user_image(user, image_class: 'border-4 rounded border-primary bg-primary w-20 h-20'), user) %>
        </div>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

app/views/events/show.html.slim
section
  = likes
  h2= event.name
  .participation= participation_link(event)
  p.meta
    span.calendar-icon=' link_to l(event.date), event_path(event, format: :ics), title: event.name, class: 'ical'
    =' t("show.hosted_by")
    = link_to_user event.user
  == link_to_route event.location

  == markdown event.description

  - if event.participants.present?
    h3= "#{t("show.attendees")} (#{event.participants.count})"
    p= render 'users/list', users: event.users

  = render "part", event: event, type: :topics
  = render "part", event: event, type: :materials

  h3#route= t("show.route")
  = map(event.location, lat: event.location.lat, long: event.location.long)

app/views/events/show.mobile.slim
h2= event.name
h5= link_to l(event.date), event_path(event, format: :ics), rel: :external
h5== "#{t("show.hosted_by")} #{link_to event.user.name, event.user}"
h5== link_to event.location.address, "#route", rel: :external

p
  - if signed_in? && current_user.participates?(event)
    = button_to t("show.not_attend"), event_participant_path(event, current_user.participation(event)), method: 'delete'
  - elsif signed_in?
    = button_to t("show.attend"), add_user_event_path(event)
  - else
    = link_to_login

div data-role="collapsible-set"
  div data-role="collapsible" class="#{event.participants.present? ? '' : 'ui-disabled'}"
    h2= t("show.attendees")
    ul data-role="listview"
      - event.users.each do |user|
        li= link_to user do
          = image_tag user.image, class: "ui-li-icon", style: "margin-top: -2px"
          = user.name
  div data-role="collapsible" class="#{event.topics.present? ? '' : 'ui-disabled'}"
    h2= t("topics")
    ul data-role="listview"
      - event.topics.each do |topic|
        li(data-role="list-divider")
          = topic.name
          - if topic.user
            == " (#{link_to(topic.user.name, topic.user)})"
        li== markdown topic.description
  div data-role="collapsible" class="#{event.materials.present? ? '' : 'ui-disabled'}"
    h2= t("show.materials")
    ul data-role="listview"
      - event.materials.each do |material|
        li data-icon="info"
          = link_to material.url do
            h3= material.name

h3#route= t("show.route")
= content_tag :p, '', id: :mobile_map, data: {url: static_map(event.location)}

app/views/events/show.slim
.card
  .card-header
    = render('badges', event: event)

  .card-body
    = render('info', event: event)
    = render('topics', event: event)
    = render('participants', event: event)
    = render('location', event: event)

  .card-footer
    small
      = I18n.tw("home.like_to_talk")
      br
      = contact_text